/*
first create a file in script i made a DeploySimpleStorage.s.sol
.s is just a foundry convention to tell that this is a script file

then i wrote the code in the DeploySimpleStorage.s.sol file which is a solidity code but it shldnt be considered a contract that we actually ever want to deploy to the blockchain, it is just a script that will help us deploy our contract SimpleStorage to the blockchain

in lib\forge-std folder we have ton of useful tools and scripts for working with foundry and the script we wrote in DeploySimpleStorage.s.sol is using the script.sol file from forge-std folder
so we import the script.sol file from forge-std folder in our DeploySimpleStorage.s.sol file

in script contract we need our main function which is going to be called run and this is the function that is going to be called when we run the script


after writing the code in the DeploySimpleStorage.s.sol file we need to run the script in the terminal to deploy the contract to the blockchain

in terminal write

"forge script script/DeploySimpleStorage.s.sol:DeploySimpleStorage "
"
 this will compile and run the script and deploy the contract to the blockchain and also give us the address of the deployed contract
the pattern is forge script <path to the script file>:<name of the contract in the script file>

well we dont have anvil running  so where does the above contract get deployed to, well it gets deployed to a temporary anvil blockchain that is created by forge and it is called ephemeral blockchain and it is created in the background when we run the above command in the terminal and it is destroyed when the command finishes running


now to deploy to anvil first we will need to start anvil in a separate terminal window and then we will need to run the command in the terminal to deploy the contract to anvil
the command will be forge script script/DeploySimpleStorage.s.sol:DeploySimpleStorage --rpc-url http://127.0.0.1:8545

the above will not bradcast the transaction to the anvil blockchain, it will just simulate the transaction and give us the address of the deployed contract but it will not actually deploy the contract to anvil blockchain

so to broadcast the code to write in terminal is
forge script script/DeploySimpleStorage.s.sol:DeploySimpleStorage --rpc-url http://127.0.0.1:8545 --broadcast --private-key <private key of the account that we want to use to deploy the contract (use anvil ki private key)>

EXPLANATION OF THE COMMAND I WROTE IN THE TERMINAL TO DEPLOY THE CONTRACT

forge script: This tells Foundry that you aren't just running a unit test or compiling code; you want to execute a deployment script file.


script/DeploySimpleStorage.s.sol:DeploySimpleStorage: This points to the exact file path (script/...) followed by a colon (:) and the specific contract name (DeploySimpleStorage) containing your run() function. It tells Forge exactly what file to look at and what contract to execute.


An RPC (Remote Procedure Call) URL is the gateway address to a blockchain network.

By pointing to http://127.0.0.1:8545, you are telling your script to connect to Anvil, which is the local, ultra-fast test blockchain running directly on your own laptop.

Note: If you were deploying to a live public network later (like Sepolia testnet or Ethereum mainnet), you would replace this local address with an Alchemy or Infura URL.

--broadcast:without it its just a dry run or a local preview of the deployment.

It isn't actually "uploaded" or published anywhere permanently. Instead, the transaction is executed locally in a temporary, isolated sandbox environment generated by Forge on your machine.

Even though you provided the Anvil RPC URL, without --broadcast, Forge uses that URL merely to fork or read the current state of the network. It runs a local simulation of the deployment against that state, but it never sends the transaction to the Anvil mempool.




Foundry will only perform Pass 1 (The Rehearsal). It will tell you in the terminal: "Simulation successful!" but if you look inside your Anvil blockchain, your contract won't be there. It never left the sandbox because you didn't give it permission to broadcast.

Adding --broadcast is like pressing the "Send" button on an email. Without it, you are just saving the email in your drafts folder.



Without --broadcast: Foundry prints the simulation logs and ends with a message like:

SIMULATION SUCCESSFUL. To broadcast these transactions, add --broadcast to the command.

With --broadcast: Foundry runs that preview first, passes it, and then you'll see a brand new section pop up in your terminal saying:

Broadcasting transactions...
📅 Block: 1
⚓ Contract Address: 0x5FbDB2315678afecb367f032d93F642f64180aa3



Passing the Anvil private key gives Forge the cryptographic authority to sign the deployment transaction using one of Anvil's pre-funded accounts (which come loaded with 10,000 fake test ETH). This pays for the gas required to deploy your SimpleStorage contract.
the private key determines who pays for the deployment and who owns/controls the deployment process. but its not where the contract gets deployed, the contract gets deployed to the anvil blockchain that is running in the background and the private key is just used to sign the transaction and pay for the gas fee






then i ran the command in the terminal to deploy the contract


*/